### ISSUE TITLE
VerifyCallback is run, but ignored, on clients.

### ISSUE THREAD

**Issue by dainnilsson** [go-noisesocket/noisesocket#1]
The return value here seems to be ignored:
https://github.com/go-noisesocket/noisesocket/blob/e6c48c7d4918def6df8f6cc7731c5c5779a7320b/conn.go#L501

Shouldn't an error here be propagated to the caller?

**Comment by Scratch-net** [comment]
Sure, you are welcome to make a PR)

**Comment by dainnilsson** [comment]
Great, PR submitted!

**Comment by Scratch-net** [comment]
Thanks, merged!
