### ISSUE TITLE
Another VerifyCallback called at the end of a handshake to handle ChannelBinding data

### ISSUE THREAD

**Issue by dnkolegov** [go-noisesocket/noisesocket#3]
Do not you think to add another VerifyCallback function triggered at the end of a handshake when ChannelBinding data will be available?
The use case is simple: to sign the hash or verify the hash (like transcript hash in TLS 1.3).
At the present time VerifyCallback can't access that data.
Does it make sense?

**Comment by Scratch-net** [comment]
Probably yes, anyway you are welcome to make a PR

**Comment by dnkolegov** [comment]
Hi @Scratch-net.
It seems my suggestion was wrong.
It is easy to add a callback where ChannelBinding data will be available. But this data is local and can not be used for peer authentication.
The primary use case (borrowed from TLS 1.3) was as follows:
1. Run a handshake.
2. Finish the handshake.
3. Take the ChannelBinding data, sign it using a private key and send to a peer.
And  I wanted to impement this natively, not on the app layer.

But ChannelBinding data obviously cannot be sent via the payload of ConnectionConfig. The current spec is not suitable to pefrom it via "payload". Please correct me if I am mistaken here. 

Any ideas or your opinion?

**Comment by Scratch-net** [comment]
Are you sure you want to sign ChannelBinding ?
Our approach was to sign static or ephemeral key and send the signature in the negotiation data
This is what implemented in https://github.com/go-noisesocket/noisesocket/tree/master/virgil sample

**Comment by dnkolegov** [comment]
Yes, I see. It would work perfectly well. But as I said before, the first idea was to use signature over ChannelBinding. Do you think Noise should not support this?

I mean that this mechanism (signed hash sending) should be implemented and supported on Noise/ Noisesocket protocol layers. Implementing this mechanism via callback is wrong from design point of view.

**Comment by Scratch-net** [comment]
I have no objections against this idea. I'm  also sure that there's no need in sending the ChannelBinding itself as it is the same as on the other side. You need to only send the signature

**Comment by dnkolegov** [comment]
Exactly. But you can do this only on application layer. You can't do this as in your example via the negitiation data. Or did I miss something?

**Comment by Scratch-net** [comment]
Ah, I understand now. Yes, there's no sense in using negotiation data for this as the handshake is not completed at that stage and as far as I know there's no special stage for that in the Noise(Socket) protocol itself. So yes, the only thing you can do right now is to fix this at the app layer

**Comment by dnkolegov** [comment]
Ok.. Thanks.
