### ISSUE TITLE
Different VerifyCallback function payload value on client- and server-sides

### ISSUE THREAD

**Issue by dnkolegov** [go-noisesocket/noisesocket#4]
I used the code in`sample/httpclientservertest`.

1. `sample/httpclientservertest/client/httpclient.go`
Configuration:
```
transport := &http.Transport{
		MaxIdleConnsPerHost: 1,
		DisableKeepAlives:   true,

		DialTLS: func(network, addr string) (net.Conn, error) {
			conn, err := noisesocket.Dial(addr, &noisesocket.ConnectionConfig{StaticKey: clientKeys, Payload: []byte{1,2,3,4,5,6}})
			if err != nil {
				fmt.Println("Dial", err)
			}

			return conn, err
		},
	}
```

2. `sample/httpclientservertest/server/httpserver.go`

Code:

```
func verifyCallback(publicKey []byte, data []byte) error {
	fmt.Println(data)
	return nil
}
...
l, err := noisesocket.Listen(":12888", &noisesocket.ConnectionConfig{StaticKey: serverKeys, VerifyCallback:verifyCallback})

```

Run client and server:

Server's output:

```
[0 0 1 2 3 4 5 6]
[0 0 1 2 3 4 5 6]
[0 0]
[0 0]
[0 0]
[0 0 1 2 3 4 5 6]
[0 0 1 2 3 4 5 6]
[0 0 1 2 3 4 5 6]
[0 0]
[0 0 1 2 3 4 5 6]
[0 0]
[0 0]
[0 0]
[0 0]
[0 0]
[0 0]
[0 0 1 2 3 4 5 6]
[0 0 1 2 3 4 5 6]
[0 0]

```
As I understand those two bytes are added by the `pad` function.
Some questions:
1) What is the goal of this padding (two zero bytes)?
2) How does the example from `virgil` work?
3) What is the suggested way to handle that padding?

Thanks.

**Comment by Scratch-net** [comment]
1) This might have been a start of some specification implementation, can't remember
2) not sure what you mean
3) for now you can simply omit those 2 zero bytes

**Comment by dnkolegov** [comment]
Ok. I see.
1 and 3 work for me.

In the 2 question I meant that 2 zero bytes are not handled in the example in the `virgil` directory.
There is the code [snippet](https://github.com/go-noisesocket/noisesocket/blob/master/virgil/server/main.go#L80) from `virgil/server/main.go`:
```
func verifyCallback(publicKey []byte, data []byte) error {
	if len(publicKey) == 0 {
		return nil
	}
	identity, signature, err := v.GetIdentityAndSignature(data)
	...
}
```
and the corresponding [definition](https://github.com/go-noisesocket/noisesocket/blob/master/virgil/helpers.go#L53) of that function:

```
func GetIdentityAndSignature(data []byte) (identity string, signature []byte, err error) {
	var info *AuthInfo
	err = json.Unmarshal(data, &info)
	if err != nil {
		return
	}

	identity = info.Identity
	signature = info.Signature
	return
}
```

Thanks.

**Comment by Scratch-net** [comment]
The sample must have been implemented before that function

**Comment by dnkolegov** [comment]
I would like to add another example. I can also "fix" your example (`virgil`) or delete `pad` function from `conn.go`. What do you prefer? Other ideas?

**Comment by Scratch-net** [comment]
Ok, so pad() was added due to this spec: 
https://noiseprotocol.org/specs/noisesocket.html#encrypted-payloads
and those 2 bytes are supposed to be there.

The proper way to fix it would be set the len to a proper uint16 value and unpad it during receive

**Comment by dnkolegov** [comment]
Ok. It works for me.

**Comment by dnkolegov** [comment]
@Scratch-net There is no problem to unpad payload. To pad we must know `noise_message_len` and `padded_len`. The last is defined in the `ConnectionConfig`,  but I wonder what is a suggested way to get `noise_message_len`?

**Comment by Scratch-net** [comment]
There's no default way for that as it involves dealing with message structure which depends on pattern, key size, etc. I don't see an easy way for that
